route53:
    image: seanponeil/route53-dyndns
    container_name: r53dyndns
    restart: always
    environment:
        - AWS_ACCESS_KEY_ID=
        - AWS_SECRET_ACCESS_KEY=
        - ROUTE53_DOMAIN_A_RECORD=
        - ROUTE53_UPDATE_FREQUENCY=10800
